swagger: '2.0'
info:
  description: PNPAA Restify Server API
  version: 1.0.0
  title: PNPAA API
host: pnpaa-api.herokuapp.com
basePath: /
schemes:
  - http
produces:
  - application/json
paths:
  /auth:
    post:
      tags:
        - Auth
      description: Get authentication token
      parameters:
        - name: email
          in: formData
          description: "User's username."
          required: true
          type: string
        - name: password
          in: formData
          description: "User's password."
          required: true
          type: string
      responses:
        '200':
          description: Auth Token Object
          schema:
            $ref: '#/definitions/AuthToken'
  /auth/verify:
    post:
      tags:
        - Auth
      description: Very if token is valid
      parameters:
        - name: Authorization
          in: header
          description: 'Authorization header. Format: `Bearer [token]`.'
          required: true
          type: string
      responses:
        '200':
          description: Token is valid
        '401':
          description: Token is has expired or has been revoked

  /discussions:
    post:
      tags:
        - Discussion
      description: Create A new discussion
      parameters:
        - name: Authorization
          in: header
          description: 'Authorization header. Format: `Bearer [token]`.'
          required: true
          type: string
        - name: Content
          in: formData
          description: Content of the post
          type: string
          required: true

      responses:
        '200':
          description: Token is valid
        '401':
          description: Token is has expired or has been revoked
definitions:
  User:
    properties:
      id:
        type: number
      name:
        type: string
      email:
        type: string
      createdAt:
        type: string
        format: dateTime
      updatedAt:
        type: string
        format: dateTime
  AuthToken:
    properties:
      user:
        $ref: '#/definitions/User'
      token:
        type: string
        description: Token to be used for every api call.
